### ISSUE TITLE
Where does the installation occur?

### ISSUE THREAD

**Issue by bcleonard** [rifelpet/osmc-cookbook#1]
Hi,

This cookbook looks great.  What I can't seem to find is where the installation of osmc occurs.

Is this cookbook for one of the osmc prebuilt images?

Thanks in advance!

Brad

**Comment by rifelpet** [comment]
@bcleonard sorry just saw this issue. I've actually been using this on a raspberry pi with the premade SD card image, so osmc is already installed at this point.

**Comment by bcleonard** [comment]
Thanks for getting back to me.

I figured that out after a while and got it working.  I forgot that I had opened this issue.

Great cookbook.  It helped me alot.

Thanks!
